# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lunarium  # ex. I m Chuan
name: Ligeng Zhu # ex. DONGChuan
email: Click here :)
emailTo: lykensyu+github@gmail.com
location: Vancouver # ex. Nice, France
company: Computational Vision Lab, Simon Fraser University
company_url: http://www.cs.sfu.ca/~colour/
github_url: https://github.com/lyken17 # ex. https://github.com/DONGChuan
github_username: Lyken17 # ex. DONGChuan
description: The sky and cosmos are one.
favicon: favicon.png # Image must be in assets/images
repository: Lyken17/lyken17.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
# url: http://localhost:4000
url: http://blog.lzhu.me

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: lunarium.disqus.com # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home
  -
    href: /blog
    label: Blog

  -
    href: /open-source
    label: Open-Source

  # -
  #   href: /bookmark
  #   label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 3 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-106086352-1'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [C, C++, Python, Lua, Scala]
reasearch_exploring_area: [Machine Learning, Deep Learning, Computer Vision]
skill_web_keywords: [HTML, CSS, JS, JQuery,Boostrap, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis]
# skill_mobile_app_keywords: [Android, Sketch UI Desgin]
